export const FETCH_TRANSCRIPTIONS = 'FETCH_TRANSCRIPTIONS';
export const FETCH_TRANSCRIPTIONS_SUCCESS = 'FETCH_TRANSCRIPTIONS_SUCCESS';
export const FETCH_TRANSCRIPTIONS_FAIL = 'FETCH_TRANSCRIPTIONS_FAIL';
export const FETCH_TRANSCRIPTIONS_MORE_SUCCESS = 'FETCH_TRANSCRIPTIONS_MORE_SUCCESS';
export const FETCH_TRANSCRIPTIONS_MORE_FAIL = 'FETCH_TRANSCRIPTIONS_MORE_FAIL';
export const FETCH_TRANSCRIPTIONS_MORE = 'FETCH_TRANSCRIPTIONS_MORE';

